- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/layouts/application.html.erb
- config/cable.yml
- config/database.yml
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20210223164326_devise_create_users.rb
- db/schema.rb
- package.json
- test/models/user_test.rb
@Nokots @DeFiDegen Hey guys, we finished adding devise to the project. If you are satisfied you can merge to master.
> Adding devise

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- db/migrate/20210223184917_add_fname_lname.rb
- db/schema.rb
can you check out the columns for users tab please
> added columns to users

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_categories.scss
- app/views/pages/home.html.erb
i've added a search bar a 4 category cards to the landing page
> added a searchbar and category cards to the landing page

- Gemfile
- Gemfile.lock
- db/seeds.rb
@DeFiDegen @GeorgiDS9 @Nokots here is the sample seed. Dont forget to pull to your local master once merged :)
> Created fuctional seed.rb

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/models/gear.rb
- config/routes.rb
- db/migrate/20210224163644_create_bookings.rb
- db/schema.rb
- test/controllers/bookings_controller_test.rb
- test/models/booking_test.rb
@DeFiDegen @GeorgiDS9 @Nokots Compelted the MVC for bookings. Dont forget to pull and bundle/yarn
> Added router,controller, and model for bookings

- app/controllers/bookings_controller.rb
- app/controllers/gears_controller.rb
- config/routes.rb
Added the show and index routes for bookings. Added the show method in bookings controller, added booking params permissions in bookings controller.
> Bookings, routes fixes + booking param permissions

- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
Added show and new actions, with new view. Simple form for the view. Very simple layout, nothing crazy. @Nokots can probably make it pretty cause he's an FE beast!
> Add show + (new + new-view)

- app/controllers/bookings_controller.rb
- app/controllers/gears_controller.rb
@DeFiDegen  please review the index and create methods in the Bookings controller. If ok, please accept. Thanks!
> Booking index create actions

- db/seeds.rb
> Added ',' to seed

- app/controllers/bookings_controller.rb
- config/routes.rb
added create. Not yet destroy.
> added create action for bookings

- app/controllers/gears_controller.rb
- app/views/pages/home.html.erb
- db/seeds.rb
@GeorgiDS9 @DeFiDegen hey guys we finished adding index filtering based on home page card selection.
> Index action category filter

- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/views/reviews/new.html.erb
- config/routes.rb
- db/migrate/20210225161910_create_reviews.rb
- db/schema.rb
- test/controllers/reviews_controller_test.rb
- test/models/review_test.rb
Completed entire MVC for Reviews. Implemented, show, new, create. Implemented reviews#new view.
Only thing now is the redirection after the, currently set to the review itself, which does not current have a view(show). 
Thinking it might be best to redirect to the actual piece of gear. Would love thoughts from the team!
> Add review model

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
the footer is now displayed as it should be
> the footer works fine now

- app/views/devise/sessions/new.html.erb
> fixed sign in glitch

- app/views/pages/home.html.erb
@landonlapensee @DeFiDegen @Nokots I have fixed the login logic. Once Laurier fixes the current login issue, you should be able to try it yourselves, but it works. Please review and merge. Thanks!
> Login logic home page

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/javascript/packs/application.js
- app/javascript/plugins/booking_calender_price_calculator.js
- app/javascript/plugins/flatpickr.js
- app/views/bookings/new.html.erb
- app/views/gears/index.html.erb
- app/views/gears/show.html.erb
- app/views/users/profile.html.erb
@stephlaf @GeorgiDS9 @Nokots pricing is finished!
> Adding price toggle

- app/controllers/gears_controller.rb
- app/views/gears/show.html.erb
- app/views/users/profile.html.erb
> Profile logic

- app/views/gears/show.html.erb
was displaying an instance of review. Changed to display review.desription and review.rating
> Small reviews display fix on gears#show view

- db/migrate/20210226163910_add_img_url_to_gears.rb
- db/schema.rb
- db/seeds.rb
@DeFiDegen @Nokots @GeorgiDS9 Here is the a new seed file with 12 gear instances! All the seed file has right now is the creation of 4 users and these 12 instances.
> Adding images to seed

- app/controllers/pages_controller.rb
- app/models/gear.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
@landonlapensee @Nokots @DeFiDegen categories are functional and have refactored the categories code. My Profile links to user profile page. Avatar logic is work in progress for which I will create a new branch shortly. Please accept and merge! Thx
> Add sports categories
